name: Node.js Package
on: push
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - run: npm test
      - run: npm run build
      - id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.npm_token }}
      - if: steps.publish.outputs.type != 'none'
        name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: docs # The branch the action should deploy to.
          folder: ./dist # The folder the action should deploy.
          target-folder: ${{steps.publish.outputs.version}}
